// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6xmCVOkZ7lLBglj0k2BKktde8AyEgeRw',
    appId: '1:10393047806:android:efa0e6d246e99e16dacbaf',
    messagingSenderId: '10393047806',
    projectId: 'taskly-19e90',
    storageBucket: 'taskly-19e90.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA_05AEBz7gbR24WpzIGNbW99SCLfDz2qM',
    appId: '1:10393047806:ios:7a709c9465933f63dacbaf',
    messagingSenderId: '10393047806',
    projectId: 'taskly-19e90',
    storageBucket: 'taskly-19e90.firebasestorage.app',
    iosBundleId: 'com.example.taskly',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA_05AEBz7gbR24WpzIGNbW99SCLfDz2qM',
    appId: '1:10393047806:ios:7a709c9465933f63dacbaf',
    messagingSenderId: '10393047806',
    projectId: 'taskly-19e90',
    storageBucket: 'taskly-19e90.firebasestorage.app',
    iosBundleId: 'com.example.taskly',
  );
}
